/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NgoIndexRouteImport } from './routes/ngo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NgoSurvivorsRouteImport } from './routes/ngo.survivors'
import { Route as NgoOrganizationRouteImport } from './routes/ngo.organization'
import { Route as NgoDashboardRouteImport } from './routes/ngo.dashboard'
import { Route as AdminNgosRouteImport } from './routes/admin.ngos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoIndexRoute = NgoIndexRouteImport.update({
  id: '/ngo/',
  path: '/ngo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoSurvivorsRoute = NgoSurvivorsRouteImport.update({
  id: '/ngo/survivors',
  path: '/ngo/survivors',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoOrganizationRoute = NgoOrganizationRouteImport.update({
  id: '/ngo/organization',
  path: '/ngo/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoDashboardRoute = NgoDashboardRouteImport.update({
  id: '/ngo/dashboard',
  path: '/ngo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNgosRoute = AdminNgosRouteImport.update({
  id: '/admin/ngos',
  path: '/admin/ngos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/organization': typeof NgoOrganizationRoute
  '/ngo/survivors': typeof NgoSurvivorsRoute
  '/admin/': typeof AdminIndexRoute
  '/ngo/': typeof NgoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/organization': typeof NgoOrganizationRoute
  '/ngo/survivors': typeof NgoSurvivorsRoute
  '/admin': typeof AdminIndexRoute
  '/ngo': typeof NgoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/organization': typeof NgoOrganizationRoute
  '/ngo/survivors': typeof NgoSurvivorsRoute
  '/admin/': typeof AdminIndexRoute
  '/ngo/': typeof NgoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/ngos'
    | '/ngo/dashboard'
    | '/ngo/organization'
    | '/ngo/survivors'
    | '/admin/'
    | '/ngo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/ngos'
    | '/ngo/dashboard'
    | '/ngo/organization'
    | '/ngo/survivors'
    | '/admin'
    | '/ngo'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/ngos'
    | '/ngo/dashboard'
    | '/ngo/organization'
    | '/ngo/survivors'
    | '/admin/'
    | '/ngo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNgosRoute: typeof AdminNgosRoute
  NgoDashboardRoute: typeof NgoDashboardRoute
  NgoOrganizationRoute: typeof NgoOrganizationRoute
  NgoSurvivorsRoute: typeof NgoSurvivorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  NgoIndexRoute: typeof NgoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/': {
      id: '/ngo/'
      path: '/ngo'
      fullPath: '/ngo/'
      preLoaderRoute: typeof NgoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/survivors': {
      id: '/ngo/survivors'
      path: '/ngo/survivors'
      fullPath: '/ngo/survivors'
      preLoaderRoute: typeof NgoSurvivorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/organization': {
      id: '/ngo/organization'
      path: '/ngo/organization'
      fullPath: '/ngo/organization'
      preLoaderRoute: typeof NgoOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/dashboard': {
      id: '/ngo/dashboard'
      path: '/ngo/dashboard'
      fullPath: '/ngo/dashboard'
      preLoaderRoute: typeof NgoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ngos': {
      id: '/admin/ngos'
      path: '/admin/ngos'
      fullPath: '/admin/ngos'
      preLoaderRoute: typeof AdminNgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNgosRoute: AdminNgosRoute,
  NgoDashboardRoute: NgoDashboardRoute,
  NgoOrganizationRoute: NgoOrganizationRoute,
  NgoSurvivorsRoute: NgoSurvivorsRoute,
  AdminIndexRoute: AdminIndexRoute,
  NgoIndexRoute: NgoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
